sequenceDiagram
  participant participant_executeAsync as executeAsync
  participant participant_runAsync as runAsync
  participant participant_toErrorMessage as toErrorMessage
  participant participant_writeStderr as writeStderr
  participant participant_writeStdout as writeStdout
  participant_runAsync->>participant_writeStdout: context.writeStdout()
  participant_writeStdout-->>participant_runAsync: return
  participant_runAsync->>participant_executeAsync: inspect.executeAsync()
  participant_executeAsync-->>participant_runAsync: return
  participant_runAsync->>participant_writeStderr: context.writeStderr()
  participant_writeStderr-->>participant_runAsync: return
  participant_runAsync->>participant_toErrorMessage: toErrorMessage()
  participant_toErrorMessage-->>participant_runAsync: return
